/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2020-04-11 06:47:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"assests/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assests/css/bootstrap-theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assests/commoncss/homestyle.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"assests/js/jquery-2.2.0.min.js\"  type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"assests/js/bootstrap.min.js\"  type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"assests/fonts/css/all.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<title>home page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"haeder\">\r\n");
      out.write("\t\t<div class=\"container-fluid history text-center \" style=\"background-color:#5AF920\">\r\n");
      out.write("\t\t\t<marquee behavior=\"alternate\">\r\n");
      out.write("\t\t\t\t<img src=\"assests/images/Online-Banking-PNG.png\" width=\"300\"\r\n");
      out.write("\t\t\t\t\theight=\"120\" alt=\"Internet Banking\" />\r\n");
      out.write("\t\t\t</marquee>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse \">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li class=\"active\"><a href=\"home.jsp\"> <i class=\"fa fa-home\" aria-hidden=\"true\"></i> Homepage</a></li>\r\n");
      out.write("        <li ><a href=\"services.jsp\">Services</a></li>\r\n");
      out.write("        <li><a href=\"contact.jsp\">Contact </a></li>\r\n");
      out.write("       \r\n");
      out.write("      </ul>\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("       \r\n");
      out.write("        <li><a href=\"logout\"> <i class=\"fa fa-sign-out\" aria-hidden=\"true\"> </i>SignOut</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar-container\">\r\n");
      out.write("  <div class=\"sidebar-logo\">\r\n");
      out.write("    ONLINE BANKING\r\n");
      out.write("  </div>\r\n");
      out.write("  <ul class=\"sidebar-navigation\">\r\n");
      out.write("    <li class=\"header\">Our Online Services</li>\r\n");
      out.write("    \r\n");
      out.write("     <li>     \r\n");
      out.write("      <a href=\"balanceservlet\" data-toggle=\"modal\" data-target=\"#pwdModal\">\r\n");
      out.write("        <i class=\"fa fa-rupee-sign\" aria-hidden=\"true\"></i> Account Balance?\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"transferamt.jsp\">\r\n");
      out.write("        <i class=\"fa fa-donate \" aria-hidden=\"true\"></i> Amount Transfer\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"Getstatement\">\r\n");
      out.write("        <i class=\"fa fa-book\" aria-hidden=\"true\"></i> Bank Statement\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"changepassword.jsp\">\r\n");
      out.write("        <i class=\"fa fa-lock\" aria-hidden=\"true\"></i> ChangePassword\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"homeloan.html\">\r\n");
      out.write("        <i class=\"fa fa-credit-card\" aria-hidden=\"true\"></i> Apply for Loan\r\n");
      out.write("      </a>\r\n");
      out.write("    </li> \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"Getstatement\">\r\n");
      out.write("        <i class=\"fa fa-cog\" aria-hidden=\"true\"></i> Privacy settings\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"#\">\r\n");
      out.write("        <i class=\"fa fa-info-circle\" aria-hidden=\"true\"></i> Information\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"content-container\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Main component for a primary marketing message or call to action -->\r\n");
      out.write("    <div class=\"jumbotron\">\r\n");
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("    <font color=\"red\"> <h1> <i class=\"fas fa-landmark  \"  style=\"color:red\"></i> Gringotts Wizarding Bank </h1></font>\r\n");
      out.write("     \r\n");
      out.write("      <p></p><br>\r\n");
      out.write("        <h1> Welcome\r\n");
      out.write("    ");
 
     out.println(session.getAttribute("Name"));
     
      out.write("  </h1>\r\n");
      out.write("      <p></p>\r\n");
      out.write("      \r\n");
      out.write("      <br><br><br><br><br> <br><br>  <br><br> <br><br>   <br><br>  <p>\r\n");
      out.write("        <a class=\"btn btn-lg btn-primary\" href=\"../../components/#navbar\" role=\"button\">More about your account &raquo;</a>\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div><br><br>\r\n");
      out.write("\r\n");
      out.write("<!-- To check balance -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"pwdModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("  <div class=\"modal-content\">      \r\n");
      out.write("      <div class=\"modal-body\">          \r\n");
      out.write("      </div>      \r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>       \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
