/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2020-04-05 15:47:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homeloan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>transfer fail</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"assests/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assests/fonts/css/all.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assests/css/bootstrap-theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"assests/js/jquery-2.2.0.min.js\"  type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"assests/js/bootstrap.min.js\"  type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"assests/commoncss/loans.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home.jsp\"><i class=\"fa fa-home\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i> Homepage</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"\">Loans</a></li>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"logout\"> <i class=\"fa fa-sign-out\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i> Sign Out\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- banner -->\r\n");
      out.write("     <section>\r\n");
      out.write("         <div class=\"container-fluid\">\r\n");
      out.write("             <div class=\"row bg-info justify-content-center align-items-center\" style=\"height: 80vh\">\r\n");
      out.write("                <div class=\"col-sm-10 text-center\">     \r\n");
      out.write("                <h1 class=\"display-2 text-capitalize\"><span class=\"text-warning\">  <i class=\"fa fa-home   \"></i> <b>  Home Loans</b></span><span class=\"text-white font-weight-bold\"></span></h1>           \r\n");
      out.write("                \r\n");
      out.write("                <form id=\"regForm\" action=\"\">\r\n");
      out.write("\r\n");
      out.write("<!-- One \"tab\" for each step in the form: -->\r\n");
      out.write("<div class=\"tab\">Name:\r\n");
      out.write("  <p><input placeholder=\"First name...\" oninput=\"this.className = ''\"></p>\r\n");
      out.write("  <p><input placeholder=\"Last name...\" oninput=\"this.className = ''\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"tab\">Contact Info:\r\n");
      out.write("  <p><input placeholder=\"E-mail...\" oninput=\"this.className = ''\"></p>\r\n");
      out.write("  <p><input placeholder=\"Phone...\" oninput=\"this.className = ''\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"tab\">Birthday:\r\n");
      out.write("  <p><input placeholder=\"dd\" oninput=\"this.className = ''\"></p>\r\n");
      out.write("  <p><input placeholder=\"mm\" oninput=\"this.className = ''\"></p>\r\n");
      out.write("  <p><input placeholder=\"yyyy\" oninput=\"this.className = ''\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"tab\">Login Info:\r\n");
      out.write("  <p><input placeholder=\"Username...\" oninput=\"this.className = ''\"></p>\r\n");
      out.write("  <p><input placeholder=\"Password...\" oninput=\"this.className = ''\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"overflow:auto;\">\r\n");
      out.write("  <div style=\"float:right;\">\r\n");
      out.write("    <button type=\"button\" id=\"prevBtn\" onclick=\"nextPrev(-1)\">Previous</button>\r\n");
      out.write("    <button type=\"button\" id=\"nextBtn\" onclick=\"nextPrev(1)\">Next</button>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Circles which indicates the steps of the form: -->\r\n");
      out.write("<div style=\"text-align:center;margin-top:40px;\">\r\n");
      out.write("  <span class=\"step\"></span>\r\n");
      out.write("  <span class=\"step\"></span>\r\n");
      out.write("  <span class=\"step\"></span>\r\n");
      out.write("  <span class=\"step\"></span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("                \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </section>\r\n");
      out.write("     <!-- end of banner -->\r\n");
      out.write("     \r\n");
      out.write("     <!-- footer -->\r\n");
      out.write("     <footer  style=\"background-color: #21d192\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row \">             \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4 text-white text-center text-md-left \">\r\n");
      out.write("                    <div class=\"py-2 my-4\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p class=\"text-white\"> <i class=\"fa fa-map-marker mx-2 \"></i>\r\n");
      out.write("                                   Bangalore \r\n");
      out.write("                        </div>\r\n");
      out.write(" \r\n");
      out.write("                        <div> \r\n");
      out.write("                            <p><i class=\"fa fa-phone  mx-2 \"></i> +91 22-27782183</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><i class=\"fa fa-envelope  mx-2\"></i><a href=\"mailto:support@eduonix.com\">abuosama838@gmail.com</a></p>\r\n");
      out.write("                        </div>  \r\n");
      out.write("                    </div>  \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4 text-white my-4 text-center text-md-left \">\r\n");
      out.write("                    <span class=\" font-weight-bold \">Designed By</span>\r\n");
      out.write("\t\t\t\t\t<p class=\"text-warning my-2\" >Osama Mustaquim</p>\r\n");
      out.write("                    <div class=\"py-2\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-facebook fa-2x text-primary mx-3\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-google-plus fa-2x text-danger mx-3\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-twitter fa-2x text-info mx-3\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-youtube fa-2x text-danger mx-3\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>  \r\n");
      out.write("        </div>\r\n");
      out.write("     </footer>\r\n");
      out.write("     <!-- end of footer -->\r\n");
      out.write("     \r\n");
      out.write("     var currentTab = 0; // Current tab is set to be the first tab (0)\r\n");
      out.write("showTab(currentTab); // Display the current tab\r\n");
      out.write("\r\n");
      out.write("function showTab(n) {\r\n");
      out.write("  // This function will display the specified tab of the form ...\r\n");
      out.write("  var x = document.getElementsByClassName(\"tab\");\r\n");
      out.write("  x[n].style.display = \"block\";\r\n");
      out.write("  // ... and fix the Previous/Next buttons:\r\n");
      out.write("  if (n == 0) {\r\n");
      out.write("    document.getElementById(\"prevBtn\").style.display = \"none\";\r\n");
      out.write("  } else {\r\n");
      out.write("    document.getElementById(\"prevBtn\").style.display = \"inline\";\r\n");
      out.write("  }\r\n");
      out.write("  if (n == (x.length - 1)) {\r\n");
      out.write("    document.getElementById(\"nextBtn\").innerHTML = \"Submit\";\r\n");
      out.write("  } else {\r\n");
      out.write("    document.getElementById(\"nextBtn\").innerHTML = \"Next\";\r\n");
      out.write("  }\r\n");
      out.write("  // ... and run a function that displays the correct step indicator:\r\n");
      out.write("  fixStepIndicator(n)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function nextPrev(n) {\r\n");
      out.write("  // This function will figure out which tab to display\r\n");
      out.write("  var x = document.getElementsByClassName(\"tab\");\r\n");
      out.write("  // Exit the function if any field in the current tab is invalid:\r\n");
      out.write("  if (n == 1 && !validateForm()) return false;\r\n");
      out.write("  // Hide the current tab:\r\n");
      out.write("  x[currentTab].style.display = \"none\";\r\n");
      out.write("  // Increase or decrease the current tab by 1:\r\n");
      out.write("  currentTab = currentTab + n;\r\n");
      out.write("  // if you have reached the end of the form... :\r\n");
      out.write("  if (currentTab >= x.length) {\r\n");
      out.write("    //...the form gets submitted:\r\n");
      out.write("    document.getElementById(\"regForm\").submit();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  // Otherwise, display the correct tab:\r\n");
      out.write("  showTab(currentTab);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateForm() {\r\n");
      out.write("  // This function deals with validation of the form fields\r\n");
      out.write("  var x, y, i, valid = true;\r\n");
      out.write("  x = document.getElementsByClassName(\"tab\");\r\n");
      out.write("  y = x[currentTab].getElementsByTagName(\"input\");\r\n");
      out.write("  // A loop that checks every input field in the current tab:\r\n");
      out.write("  for (i = 0; i < y.length; i++) {\r\n");
      out.write("    // If a field is empty...\r\n");
      out.write("    if (y[i].value == \"\") {\r\n");
      out.write("      // add an \"invalid\" class to the field:\r\n");
      out.write("      y[i].className += \" invalid\";\r\n");
      out.write("      // and set the current valid status to false:\r\n");
      out.write("      valid = false;\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  // If the valid status is true, mark the step as finished and valid:\r\n");
      out.write("  if (valid) {\r\n");
      out.write("    document.getElementsByClassName(\"step\")[currentTab].className += \" finish\";\r\n");
      out.write("  }\r\n");
      out.write("  return valid; // return the valid status\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fixStepIndicator(n) {\r\n");
      out.write("  // This function removes the \"active\" class of all steps...\r\n");
      out.write("  var i, x = document.getElementsByClassName(\"step\");\r\n");
      out.write("  for (i = 0; i < x.length; i++) {\r\n");
      out.write("    x[i].className = x[i].className.replace(\" active\", \"\");\r\n");
      out.write("  }\r\n");
      out.write("  //... and adds the \"active\" class to the current step:\r\n");
      out.write("  x[n].className += \" active\";\r\n");
      out.write("}\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
