/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2020-03-26 07:30:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class launchsignin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>launching Sign in page</title>\r\n");
      out.write("<link href=\"assets/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" >\r\n");
      out.write("<script src=\"assets/js/jquery-2.2.0.min.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--Modal: Login / Register Form-->\r\n");
      out.write("<div class=\"modal fade\" id=\"modalLRForm\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog cascading-modal\" role=\"document\">\r\n");
      out.write("    <!--Content-->\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!--Modal cascading tabs-->\r\n");
      out.write("      <div class=\"modal-c-tabs\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Nav tabs -->\r\n");
      out.write("        <ul class=\"nav nav-tabs md-tabs tabs-2 light-blue darken-3\" role=\"tablist\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" data-toggle=\"tab\" href=\"#panel7\" role=\"tab\"><i class=\"fas fa-user mr-1\"></i>\r\n");
      out.write("              Login</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" data-toggle=\"tab\" href=\"#panel8\" role=\"tab\"><i class=\"fas fa-user-plus mr-1\"></i>\r\n");
      out.write("              Register</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <!-- Tab panels -->\r\n");
      out.write("        <div class=\"tab-content\">\r\n");
      out.write("          <!--Panel 7-->\r\n");
      out.write("          <div class=\"tab-pane fade in show active\" id=\"panel7\" role=\"tabpanel\">\r\n");
      out.write("\r\n");
      out.write("            <!--Body-->\r\n");
      out.write("            <div class=\"modal-body mb-1\">\r\n");
      out.write("              <div class=\"md-form form-sm mb-5\">\r\n");
      out.write("                <i class=\"fas fa-envelope prefix\"></i>\r\n");
      out.write("                <input type=\"email\" id=\"modalLRInput10\" class=\"form-control form-control-sm validate\">\r\n");
      out.write("                <label data-error=\"wrong\" data-success=\"right\" for=\"modalLRInput10\">Your email</label>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"md-form form-sm mb-4\">\r\n");
      out.write("                <i class=\"fas fa-lock prefix\"></i>\r\n");
      out.write("                <input type=\"password\" id=\"modalLRInput11\" class=\"form-control form-control-sm validate\">\r\n");
      out.write("                <label data-error=\"wrong\" data-success=\"right\" for=\"modalLRInput11\">Your password</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"text-center mt-2\">\r\n");
      out.write("                <button class=\"btn btn-info\">Log in <i class=\"fas fa-sign-in ml-1\"></i></button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--Footer-->\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("              <div class=\"options text-center text-md-right mt-1\">\r\n");
      out.write("                <p>Not a member? <a href=\"#\" class=\"blue-text\">Sign Up</a></p>\r\n");
      out.write("                <p>Forgot <a href=\"#\" class=\"blue-text\">Password?</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-outline-info waves-effect ml-auto\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--/.Panel 7-->\r\n");
      out.write("\r\n");
      out.write("          <!--Panel 8-->\r\n");
      out.write("          <div class=\"tab-pane fade\" id=\"panel8\" role=\"tabpanel\">\r\n");
      out.write("\r\n");
      out.write("            <!--Body-->\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("              <div class=\"md-form form-sm mb-5\">\r\n");
      out.write("                <i class=\"fas fa-envelope prefix\"></i>\r\n");
      out.write("                <input type=\"email\" id=\"modalLRInput12\" class=\"form-control form-control-sm validate\">\r\n");
      out.write("                <label data-error=\"wrong\" data-success=\"right\" for=\"modalLRInput12\">Your email</label>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"md-form form-sm mb-5\">\r\n");
      out.write("                <i class=\"fas fa-lock prefix\"></i>\r\n");
      out.write("                <input type=\"password\" id=\"modalLRInput13\" class=\"form-control form-control-sm validate\">\r\n");
      out.write("                <label data-error=\"wrong\" data-success=\"right\" for=\"modalLRInput13\">Your password</label>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"md-form form-sm mb-4\">\r\n");
      out.write("                <i class=\"fas fa-lock prefix\"></i>\r\n");
      out.write("                <input type=\"password\" id=\"modalLRInput14\" class=\"form-control form-control-sm validate\">\r\n");
      out.write("                <label data-error=\"wrong\" data-success=\"right\" for=\"modalLRInput14\">Repeat password</label>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"text-center form-sm mt-2\">\r\n");
      out.write("                <button class=\"btn btn-info\">Sign up <i class=\"fas fa-sign-in ml-1\"></i></button>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--Footer-->\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("              <div class=\"options text-right\">\r\n");
      out.write("                <p class=\"pt-1\">Already have an account? <a href=\"#\" class=\"blue-text\">Log In</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-outline-info waves-effect ml-auto\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--/.Panel 8-->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--/.Content-->\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--Modal: Login / Register Form-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("  <a href=\"\" class=\"btn btn-default btn-rounded my-3\" data-toggle=\"modal\" data-target=\"#modalLRForm\">Launch\r\n");
      out.write("    Modal LogIn/Register</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
