/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2020-04-06 12:43:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class transferamt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title> Amount transfer</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"assests/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assests/fonts/css/all.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assests/css/bootstrap-theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"assests/js/jquery-2.2.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"assests/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".body{\r\n");
      out.write("background:\"red\"\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"well\">\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home.jsp\"><i class=\"fa fa-home\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i> Homepage</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"\">Transactions</a></li>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"logout\"> <i class=\"fa fa-sign-out\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i> Sign Out\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"content-container\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Main component for a primary marketing message or call to action -->\r\n");
      out.write("    <div class=\"jumbotron\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"content-container\">\r\n");
      out.write("\t<div class=\"container-fluid history text-center \">\r\n");
      out.write("\t<p class=\"text-success\"><h2></h2></p>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    \r\n");
      out.write("\t<div class=\"row justify-content-md-center\">\r\n");
      out.write("\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t<div class=\"card border-primary\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header bg-primary text-center\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"card-title\">Amount Transfer</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body justify-content-center\">\r\n");
      out.write("\t\t\t\t\t<form accept-charset=\"UTF-8\" role=\"form\" action=\"Transferservlet\"\r\n");
      out.write("\t\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"> Account Number</span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" placeholder=\"\" name=\"toacc\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\">Beneficiary Name</span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" placeholder=\"\" name=\"accholdername\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\">Amount to transfer</span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" placeholder=\"\" name=\"tamount\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\">Enter current date</span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"date\" placeholder=\"\" name=\"date\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"btn btn-lg btn-info btn-block\" type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"Send\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"home.jsp\" class=\"btn btn-lg btn-warning btn-block\">Cancel</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("     <footer  style=\"background-color: #21d192\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row \">             \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4 text-white text-center text-md-left \">\r\n");
      out.write("                    <div class=\"py-2 my-4\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p class=\"text-white\"> <i class=\"fa fa-map-marker mx-2 \"></i>\r\n");
      out.write("                                   Bangalore \r\n");
      out.write("                        </div>\r\n");
      out.write(" \r\n");
      out.write("                        <div> \r\n");
      out.write("                            <p><i class=\"fa fa-phone  mx-2 \"></i> +91 22-27782183</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><i class=\"fa fa-envelope  mx-2\"></i><a href=\"mailto:support@eduonix.com\">abuosama838@gmail.com</a></p>\r\n");
      out.write("                        </div>  \r\n");
      out.write("                    </div>  \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4 text-white my-4 text-center text-md-left \">\r\n");
      out.write("                    <span class=\" font-weight-bold \">Designed By</span>\r\n");
      out.write("\t\t\t\t\t<p class=\"text-warning my-2\" >Osama Mustaquim</p>\r\n");
      out.write("                    <div class=\"py-2\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-facebook fa-2x text-primary mx-3\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-google-plus fa-2x text-danger mx-3\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-twitter fa-2x text-info mx-3\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fab fa-youtube fa-2x text-danger mx-3\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>  \r\n");
      out.write("        </div>\r\n");
      out.write("     </footer>\r\n");
      out.write("     <!-- end of footer -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
